# Run first time try `docker compose up -f stack.yml -d`

version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME: postgres
    ports:
      - 3002:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080